.TH KNP 1 "May 2, 1999"
.SH 名称
knp \- 日本語構文解析システム
.SH 形式
.B knp
[
.B [\-case|dpnd|bnst|disc] [\-tree|sexp] [\-normal|detail|debug] 
[\-expand] [\-C host[:port]] [\-S] [\-N port]
]
.SH 解説
.B knp
は、構文解析システムです。'juman -B -e' の出力を入力として受け取ります。
.PP
次のようなオプションがあります。
.TP
.B \-case
格解析を行います。
.TP
.B \-dpnd
依存構造解析を行います。(デフォルト)
.TP
.B \-bnst
文節化のみを行います。
.TP
.B \-disc
文脈解析を行います。
.TP
.B \-S
KNP サーバを立ち上げます。
.TP
.B \-N port
KNP サーバのポート番号を指定します。デフォルトは 33000 です。
.TP
.B \-C host[:port]
KNP サーバに接続します。
.TP
.B \-tab
計算機で後処理することが容易なフォーマットで出力します。
.PP
.SH 関連事項
.BR juman (1)
.SH バグ
あるかもしれません。
.SH 著者
knp@pine.kuee.kyoto-u.ac.jp
