#ifndef CONTEXT_H
#define CONTEXT_H

#define	SVM_FREQ_SD	112.24212 /* for np */
// #define	SVM_FREQ_SD	49.72895 /* for 2002_10_17 (cook-only) */
// #define	SVM_FREQ_SD	29.98034 /* for 2002_11_19 (cook-only) */

#define	SVM_FREQ_SD_NO	504.70998 /* for noun, np */

#define	LOC_PARENTV	0x000002
#define	LOC_PARENTV_MC	0x000003
#define	LOC_CHILDPV	0x000200
#define	LOC_CHILDV	0x000400
#define	LOC_PARENTNPARENTV	0x000004
#define	LOC_PARENTNPARENTV_MC	0x000005
#define	LOC_PV		0x000008
#define	LOC_PV_MC	0x000009
#define	LOC_PARENTVPARENTV	0x000010
#define	LOC_PARENTVPARENTV_MC	0x000011
#define	LOC_MC		0x002001
#define	LOC_SC		0x004000
#define	LOC_PRE_OTHERS	0x008000
#define	LOC_POST_OTHERS	0x009000
#define	LOC_S1_MC	0x012001
#define	LOC_S1_SC	0x014000
#define	LOC_S1_OTHERS	0x010000
#define	LOC_S2_MC	0x022001
#define	LOC_S2_SC	0x024000
#define	LOC_S2_OTHERS	0x020000
#define	LOC_OTHERS	0x000000
/* LOC: 17文字が最大 */
/* 位置の数を変えた場合 const.h の LOC_NUMBER を更新すること */


/* for np */
int LocationOrder[][LOC_NUMBER] = {
    {END_M},
    {LOC_PARENTNPARENTV, LOC_PARENTV_MC, LOC_PARENTVPARENTV, LOC_PARENTV, LOC_PARENTNPARENTV_MC,
     LOC_PV_MC, LOC_CHILDPV, LOC_PV, LOC_PARENTVPARENTV_MC, LOC_CHILDV, LOC_MC, LOC_S1_MC,
     LOC_SC, LOC_S1_SC, LOC_S2_MC, LOC_PRE_OTHERS, LOC_S2_SC, LOC_POST_OTHERS,
     LOC_S1_OTHERS, LOC_S2_OTHERS, END_M},
    {LOC_CHILDV, LOC_PARENTVPARENTV, LOC_PV, LOC_CHILDPV, LOC_PARENTVPARENTV_MC,
     LOC_PARENTNPARENTV, LOC_PARENTV, LOC_PV_MC, LOC_PARENTNPARENTV_MC, LOC_PARENTV_MC,
     LOC_PRE_OTHERS, LOC_S1_MC, LOC_S2_MC, LOC_MC, LOC_SC, LOC_S1_SC, LOC_S1_OTHERS,
     LOC_S2_SC, LOC_POST_OTHERS, LOC_S2_OTHERS, END_M},
    {LOC_PV, LOC_PARENTVPARENTV, LOC_PARENTNPARENTV, LOC_CHILDPV, LOC_CHILDV,
     LOC_PARENTV, LOC_PARENTVPARENTV_MC, LOC_PARENTV_MC, LOC_S1_MC, LOC_PV_MC,
     LOC_S1_SC, LOC_SC, LOC_PRE_OTHERS, LOC_MC, LOC_PARENTNPARENTV_MC, LOC_S2_MC,
     LOC_S2_SC, LOC_S1_OTHERS, LOC_POST_OTHERS, LOC_S2_OTHERS, END_M},
};


/* for 2002_10_17 *
int LocationOrder[][LOC_NUMBER] = {
    {END_M}, 
    {LOC_PV_MC, LOC_PARENTV, LOC_MC, LOC_CHILDPV, LOC_PARENTV_MC, LOC_SC, 
     LOC_CHILDV, LOC_PARENTNPARENTV_MC, LOC_PARENTVPARENTV_MC, LOC_S1_MC, 
     LOC_PRE_OTHERS, LOC_S2_MC, LOC_S1_SC, LOC_S1_OTHERS, LOC_S2_OTHERS, 
     LOC_S2_SC, LOC_POST_OTHERS, END_M}, 
    {LOC_PARENTV_MC, LOC_SC, LOC_CHILDV, LOC_PARENTV, LOC_PARENTNPARENTV, 
     LOC_PARENTVPARENTV_MC, LOC_CHILDPV, LOC_S1_SC, LOC_S1_MC, LOC_PARENTNPARENTV_MC, 
     LOC_S1_OTHERS, LOC_S2_MC, LOC_PRE_OTHERS, LOC_MC, LOC_S2_SC, LOC_POST_OTHERS, LOC_S2_OTHERS, 
     END_M}, 
    {LOC_PARENTNPARENTV, LOC_CHILDPV, LOC_PV_MC, LOC_SC, LOC_CHILDV, 
     LOC_PARENTNPARENTV_MC, LOC_PARENTV_MC, LOC_S1_MC, LOC_S1_OTHERS, LOC_PARENTV, 
     LOC_S1_SC, LOC_S2_MC, LOC_S2_SC, LOC_PARENTVPARENTV_MC, LOC_PRE_OTHERS, 
     LOC_S2_OTHERS, LOC_POST_OTHERS, END_M}, 
};
*/

/* for 2002_11_19 *
int LocationOrder[][LOC_NUMBER] = {
    {END_M}, 
    {LOC_PV_MC, LOC_PARENTV, LOC_CHILDPV, LOC_MC, LOC_PARENTV_MC, LOC_PARENTNPARENTV_MC, 
     LOC_PV, LOC_SC, LOC_PARENTVPARENTV_MC, LOC_CHILDV, LOC_S1_MC, 
     LOC_PRE_OTHERS, LOC_S1_SC, LOC_S2_MC, LOC_S1_OTHERS, LOC_S2_OTHERS, 
     LOC_S2_SC, LOC_POST_OTHERS, END_M}, 
    {LOC_PARENTVPARENTV, LOC_PARENTV_MC, LOC_SC, LOC_CHILDV, LOC_PARENTNPARENTV, LOC_PARENTV, 
     LOC_PARENTNPARENTV_MC, LOC_S1_MC, LOC_S1_SC, LOC_PARENTVPARENTV_MC, LOC_CHILDPV, 
     LOC_PRE_OTHERS, LOC_S2_SC, LOC_S1_OTHERS, LOC_S2_MC, LOC_MC, LOC_S2_OTHERS, LOC_POST_OTHERS, 
     END_M}, 
    {LOC_PARENTNPARENTV, LOC_CHILDPV, LOC_SC, LOC_PARENTV_MC, LOC_CHILDV, 
     LOC_PARENTNPARENTV_MC, LOC_PV_MC, LOC_S1_SC, LOC_S1_MC, LOC_S2_MC, LOC_S1_OTHERS, LOC_PARENTV, 
     LOC_PARENTVPARENTV_MC, LOC_S2_SC, LOC_MC, LOC_PRE_OTHERS, 
     LOC_S2_OTHERS, LOC_POST_OTHERS, END_M}, 
};
*/

#endif
