#=============================================================================
#
#	GNU make "Makefile" for KN-PARSER (Dictionary Database)
#
#		1995/07/10  Sadao Kurohashi (kuro@kuee.kyoto-u.ac.jp)
#
#=============================================================================

#----------------------------------------
#	Search Paths
#----------------------------------------

KNP_DIR  := /share/tool/knp
TEMPDIR  := /tmp
MAKE_DB  := ../system/make_db
IPAL_CMD := ../system/ipal

BGH_FILE    := /share/dict/bgh/monitor/sakuin
EDR_FILE    := /share/dict/EDR/tdict/jwd/JWD.DIC

IPALV1_FILE := /share/dict/ipal/orig/dousi1/dousi1.txt
IPALV2_FILE := /share/dict/ipal/orig/dousi2/dousi2.txt
IPALA1_FILE := /share/dict/ipal/orig/keiyou/keiyou1.txt
IPALA2_FILE := /share/dict/ipal/orig/keiyou/keiyou2.txt
IPALN_DIR   := /share/dict/ipal_noun_31/3.1/data

WORD2CODE   := /share/dict/ntt/data/word2code
SM2CODE     := /share/dict/ntt/data/sm2code
CODE2SM     := /share/dict/ntt/data/code2sm
SMP2SMG     := /share/dict/ntt/data/smp2smg

KNP_SYS  := $(KNP_DIR)/system
KNP_DICT := $(KNP_DIR)/dict

#----------------------------------------
#	Compiler Options
#----------------------------------------

RMF       := rm -f

#----------------------------------------
#	Default Targets
#----------------------------------------

all : make_dir make_database make_hashdb

#----------------------------------------
#	Target(0): make_dir
#----------------------------------------

make_dir :
	if [ ! -d bgh ]; then \
		mkdir bgh; \
	fi
	if [ ! -d scase ]; then \
		mkdir scase; \
	fi
	if [ ! -d cf ]; then \
		mkdir cf; \
	fi
	if [ ! -d sm ]; then \
		mkdir sm; \
	fi

#----------------------------------------
#	Target(1): make_database
#----------------------------------------

make_database :
	if [ -f "$(BGH_FILE)" ]; then \
		nkf -S -e < "$(BGH_FILE)" | src/bgh.pl > bgh/bgh.dat; \
	fi
	if [ -f "$(EDR_FILE)" ]; then \
		src/edr.pl < "$(EDR_FILE)" > scase/scase.dat; \
	fi
	if [ -f "$(IPALV1_FILE)" -a "$(IPALV2_FILE)" ]; then \
		cat $(IPALV1_FILE) $(IPALV2_FILE) | src/ipalv.pl > cf/ipalv.dat; \
	fi
	if [ -f "$(IPALA1_FILE)" -a "$(IPALA2_FILE)" ]; then \
		src/ipala.pl $(IPALA1_FILE) $(IPALA2_FILE) > cf/ipala.dat; \
	fi
	if [ -n "$(IPALN_DIR)" -a -d "$(IPALN_DIR)" ]; then \
		cat $(IPALN_DIR)/n31.* | src/ipals.pl | src/ipals_add_voice.pl > cf/ipals.dat; \
	fi
	if [ -f cf/ipalv.dat -o -f cf/ipals.dat -o -f cf/ipala.dat ]; then \
		cat cf/ipalv.dat cf/ipals.dat cf/ipala.dat | $(IPAL_CMD) cf/ipal.idx cf/ipal.dat; \
		cat cf/ipalv.dat cf/ipals.dat cf/ipala.dat | src/ipal2scase.pl >> scase/scase.dat; \
	fi

#----------------------------------------
#	Target(2): make_hashdb
#----------------------------------------

make_hashdb :
	if [ -f bgh/bgh.dat ]; then \
		$(MAKE_DB) $(TEMPDIR)/bgh < bgh/bgh.dat; \
		mv $(TEMPDIR)/bgh bgh/bgh; \
	fi
	if [ -f $(WORD2CODE) ]; then \
		$(MAKE_DB) $(TEMPDIR)/word2code < $(WORD2CODE); \
		mv $(TEMPDIR)/word2code sm/word2code; \
	fi
	if [ -f $(SM2CODE) ]; then \
		$(MAKE_DB) $(TEMPDIR)/sm2code < $(SM2CODE); \
		mv $(TEMPDIR)/sm2code sm/sm2code; \
	fi
	if [ -f $(CODE2SM) ]; then \
		$(MAKE_DB) $(TEMPDIR)/code2sm < $(CODE2SM); \
		mv $(TEMPDIR)/code2sm sm/code2sm; \
	fi
	if [ -f $(SMP2SMG) ]; then \
		$(MAKE_DB) $(TEMPDIR)/smp2smg -append / < $(SMP2SMG); \
		mv $(TEMPDIR)/smp2smg sm/smp2smg; \
	fi
	if [ -f scase/scase.dat ]; then \
		$(MAKE_DB) $(TEMPDIR)/scase -or < scase/scase.dat; \
		mv $(TEMPDIR)/scase scase/scase; \
	fi
	if [ -f cf/ipal.idx ]; then \
		$(MAKE_DB) $(TEMPDIR)/ipal -append / < cf/ipal.idx; \
		mv $(TEMPDIR)/ipal cf/ipal; \
	fi

#----------------------------------------
#	Target(3): clean
#----------------------------------------

clean : clean_db

clean_db :
	$(RMF) bgh/*
	$(RMF) scase/*
	$(RMF) cf/* 

#=============================================================================
