# -*- Makefile -*-
#=============================================================================
#
#	Configuration file for KN-PARSER (Dictionary Database)
#
#		1995/07/10  Sadao Kurohashi (kuro@kuee.kyoto-u.ac.jp)
#
#=============================================================================

#----------------------------------------
#	Search Paths
#----------------------------------------

KNP_DIR  := /share/tool/knp
KNP_SYS  := $(KNP_DIR)/system
KNP_DICT := $(KNP_DIR)/dict

TEMPDIR  := /tmp
MAKE_DB  := ../system/make_db
CF_CMD   := ../system/ipal
DBEXT    := 

BGH_FILE    := /share/dict/bgh/monitor/sakuin
EDR_FILE    := /share/dict/EDR/tdict/jwd/JWD.DIC

IPALV1_FILE := /share/dict/ipal/orig/dousi1/dousi1.txt
IPALV2_FILE := /share/dict/ipal/orig/dousi2/dousi2.txt
IPALA1_FILE := /share/dict/ipal/orig/keiyou/keiyou1.txt
IPALA2_FILE := /share/dict/ipal/orig/keiyou/keiyou2.txt
IPALN_DIR   := /share/dict/ipal_noun_31/3.1/data

SM2BGHCODE  := bgh/sm2code.dat
WORD2CODE   := sm/word2code.dat
SM2CODE     := sm/sm2code.dat
CODE2SM     := sm/code2sm.dat
SMP2SMG     := sm/smp2smg.dat

#=============================================================================
